import:
  - config1-contexts.yaml

pipelines:
  pipeline1:
    - task: a
    - task: b
      depends: ["a"]
    - task: c
      depends: ["a"]
    - task: d
      depends: ["b", "c"]
    - task: e
      depends: ["a", "b", "c", "d"]

  pipeline2:
    - task: a
    - task: b
    - task: e
      depends: ["a", "b"]

  pipeline3:
    - task: env

tasks:
  a:
    command:
      - echo "A"
      - export CCC=1

  b:
    command:
      - echo "B"

  c:
    command:
      - echo "C"

  d:
    command:
      - echo "D"

  e:
    context: alpine
    command:
      - echo "E"

  env:
    command:
      - echo ${TEST}
