pipelines:
  pipeline-with-error:
    tasks:
      - task: b

  pipeline-with-args:
    tasks:
      - task: c

tasks:
  a:
    command:
      - echo "A"

  b:
    command:
      - ">&2 echo \"error\" && exit 1"

  c:
    command:
      - echo "C - ${ARGS}"
