pipelines:
  cyclic-pipeline1:
    tasks:
      - task: task1
        depends_on: task3
      - task: task2
        depends_on: task1
      - task: task3
        depends_on: task2

tasks:
  task1:
    command:
      - echo TASK1

  task2:
    command:
      - echo TASK2

  task3:
    command:
      - echo TASK3
