contexts:
  local:
    type: local
    env:
      TEST: test-value

  alpine:
    type: container
    container:
      provider: docker-compose
      name: alpine
      options:
        - --file=example/docker-compose.yaml

