import:
  - config1-contexts.yaml

pipelines:
  pipeline1:
    tasks:
      - task: a
      - task: b
        depends_on: a
      - task: c
        depends_on: a
      - task: d
        depends_on: ["b", "c"]
      - task: e
        depends_on: ["a", "b", "c", "d"]

  pipeline2:
    tasks:
    - task: a
    - task: b
    - task: e
      depends_on: ["a", "b"]

  pipeline3:
    tasks:
    - task: env

tasks:
  a:
    command:
      - echo "A"
      - export CCC=1

  b:
    command:
      - echo "B"

  c:
    command:
      - echo "C"

  d:
    command:
      - echo "D"

  e:
    context: alpine
    command:
      - echo "E"
    env:
      AAA: BBB

  env:
    command:
      - echo ${TEST}
