name: Go
on: [create]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: GOOS=darwin GOARCH=amd64 go build -o wilson -v .
      
    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "wilson"
        token: ${{ secrets.GITHUB_TOKEN }}
