name: Release
on: [create]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install wilson
      run: |
        go get -u github.com/trntv/wilson
        wilson help

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: |
        wilson run build
        tar -zcvf bin/wilson-darwin-amd64.tar.gz bin/wilson_darwin_amd64
        tar -zcvf bin/wilson-linux-amd64.tar.gz bin/wilson_linux_amd64


    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/wilson-linux-amd64.tar.gz, bin/wilson-darwin-amd64.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
